### ISSUE TITLE
I can't log into the system

### ISSUE THREAD

**Issue by xiao12mm** [zilliztech/attu#161]
### Discussed in https://github.com/zilliztech/attu/discussions/159

<div type='discussions-op-text'>

<sup>Originally posted by **xiao12mm** December 23, 2022</sup>
the code:
`docker run -p 8000:3000 -e HOST_URL=http://{ your machine IP }:8000 -e MILVUS_URL={your machine IP}:19530 zilliz/attu:latest`

I changed the IP address, so I can open the login page, but I can't log in.

</div>

**Comment by nameczz** [comment]
If you open auth in milvus.yml, your Default user is root, password is Milvus.
related doc: https://milvus.io/docs/authenticate.md#Create-an-authenticated-user.
If default auth can't solve your problem, could you please upload a screenshot of the error?
@xiao12mm

**Comment by lpasselin** [comment]
Same problem here, even with default user and password.

**Comment by echo-initial** [comment]
Version 2.1 cannot log in after using the default user name and password

```
Error: Error: 14 UNAVAILABLE: No connection established
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/index.js:28:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  expose: true,
  statusCode: 400,
  status: 400
}
POST /api/v1/milvus/connect 400 Error: Error: 14 UNAVAILABLE: No connection established

 POST undefined /api/v1/milvus/connect undefined ms @ Mon, 06 Mar 2023 09:52:05 GMT ::ffff:101.207.139.251 from undefined Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
```

**Comment by echo-initial** [comment]
I modified the port ，can successfully log in after installing ATTU in the windows, but cannot log in after installing with Docker Composite.

this is request
```
address: "--------:19531"
password: ""
ssl: false
username: "root"
```

The error is the same as above

**Comment by tzh001234** [comment]
请问解决了吗

**Comment by wilac-pv** [comment]
登录没反应

**Comment by forestmgy** [comment]
same issues here 
log info as follows:
```
Error: Error: 14 UNAVAILABLE: No connection established
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/index.js:28:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  expose: true,
  statusCode: 400,
  status: 400
}
POST /api/v1/milvus/connect 400 Error: Error: 14 UNAVAILABLE: No connection established

 POST 400 /api/v1/milvus/connect 77.849 ms @ Tue, 16 May 2023 10:03:43 GMT ::ffff:172.17.0.1 from undefined Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
```

**Comment by LinightKira** [comment]
登不进去，点击连接报400 Bad Request

**Comment by Ximu-Luya** [comment]
> same issues here 同样的问题在这里 log info as follows:日志信息如下：
> 
> ```
> Error: Error: 14 UNAVAILABLE: No connection established
>     at /app/node_modules/@zilliz/milvus2-sdk-node/dist/utils/index.js:28:15
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   expose: true,
>   statusCode: 400,
>   status: 400
> }
> POST /api/v1/milvus/connect 400 Error: Error: 14 UNAVAILABLE: No connection established
> 
>  POST 400 /api/v1/milvus/connect 77.849 ms @ Tue, 16 May 2023 10:03:43 GMT ::ffff:172.17.0.1 from undefined Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
> ```

Me too, the same problem can be reproduced here. 

My milvus runs on my own server through docker compose. I have confirmed that I have enabled the firewall on port 19530 of the server, and confirmed that it can be connected through nc -vz \<my server host\> 19530.

**Comment by shanghaikid** [comment]
> 

what's your milvus version?

**Comment by shanghaikid** [comment]
> 

If you running attu from docker, the ip or address you entered into attu's login page, it should be accessible from attu's docker network.

**Comment by echo-initial** [comment]
1. You should use a specific version, such as v2.2.5, instead of latest
2. Check firewall or security group policies

**Comment by geminigeek** [comment]
> 登录没反应

having same issue ?

**Comment by shanghaikid** [comment]
> 
Some questions:

- What's your milvus version? 
- What's your attu version? 
- docker  or standalone application ?

**Comment by geminigeek** [comment]
> > 
> 
> Some questions:
> 
> * What's your milvus version?
> * What's your attu version?
> * docker  or standalone application ?

hi,

i solved this my self, i was adding attu in milvus bootcamp reverse image search demo , reading from this page https://milvus.io/docs/attu_install-docker.md , as this page do not mention network line for docker compose, i added these lines as it is and it was not working!, now i added network line in the docker compose file it works. here is my fix if it help a newbie , if you have a default network this line is not needed . line added

```
networks:
      app_net:
        ipv4_address: 172.16.238.14
```
working attu block for reverse search demo

```
attu:
    container_name: attu
    image: zilliz/attu:v2.2.7
    networks:
      app_net:
        ipv4_address: 172.16.238.14
    environment:
      MILVUS_URL: milvus-standalone:19530
    ports:
      - "8000:3000"
    depends_on:
      - "standalone"
```

**Comment by renzhichaos** [comment]
楼上正解, 如果添加了networks配置, 要在一个网关内配置ip

**Comment by winqihe** [comment]
```version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.12
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
 
  attu:
   container_name: attu
   image: zilliz/attu:v2.2.7
   environment:
     MILVUS_URL: milvus-standalone:19530
   ports:
     - "8000:3000"
   depends_on:
     - "standalone"
```
this is my docker-compose.yml, hope can help you !

**Comment by wisdomtooth546** [comment]
> ```
> 
> services:
>   etcd:
>     container_name: milvus-etcd
>     image: quay.io/coreos/etcd:v3.5.5
>     environment:
>       - ETCD_AUTO_COMPACTION_MODE=revision
>       - ETCD_AUTO_COMPACTION_RETENTION=1000
>       - ETCD_QUOTA_BACKEND_BYTES=4294967296
>       - ETCD_SNAPSHOT_COUNT=50000
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
>     command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
> 
>   minio:
>     container_name: milvus-minio
>     image: minio/minio:RELEASE.2023-03-20T20-16-18Z
>     environment:
>       MINIO_ACCESS_KEY: minioadmin
>       MINIO_SECRET_KEY: minioadmin
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
>     command: minio server /minio_data
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
>       interval: 30s
>       timeout: 20s
>       retries: 3
> 
>   standalone:
>     container_name: milvus-standalone
>     image: milvusdb/milvus:v2.2.12
>     command: ["milvus", "run", "standalone"]
>     environment:
>       ETCD_ENDPOINTS: etcd:2379
>       MINIO_ADDRESS: minio:9000
>     volumes:
>       - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
>     ports:
>       - "19530:19530"
>       - "9091:9091"
>     depends_on:
>       - "etcd"
>       - "minio"
>  
>   attu:
>    container_name: attu
>    image: zilliz/attu:v2.2.7
>    environment:
>      MILVUS_URL: milvus-standalone:19530
>    ports:
>      - "8000:3000"
>    depends_on:
>      - "standalone"
> ```
> 
> this is my docker-compose.yml, hope can help you !

This works! Make sure to use root as the username.

**Comment by ycqu** [comment]
http://10.224.0.222:8000/#/connect
![image](https://github.com/zilliztech/attu/assets/58884839/794e8e9b-3848-43ab-9cc0-8023b8dac459) 
Click connect no response, dockers log below
![image](https://github.com/zilliztech/attu/assets/58884839/f3c032fa-535e-4439-83e0-aed5202d6d18)

container info:
![image](https://github.com/zilliztech/attu/assets/58884839/54eba3da-8b87-4375-b2a0-71a1cfbdd156)

How to solve it?

**Comment by shanghaikid** [comment]
> http://10.224.0.222:8000/#/connect ![image](https://user-images.githubusercontent.com/58884839/275702384-794e8e9b-3848-43ab-9cc0-8023b8dac459.png) Click connect no response, dockers log below ![image](https://user-images.githubusercontent.com/58884839/275702482-f3c032fa-535e-4439-83e0-aed5202d6d18.png)
> 
> container info: ![image](https://user-images.githubusercontent.com/58884839/275702879-54eba3da-8b87-4375-b2a0-71a1cfbdd156.png)
> 
> How to solve it?

make sure the ip `10.224.0.222` can be accessible from the attu docker.

**Comment by ycqu** [comment]
> make sure the ip `10.224.0.222` can be accessible from the attu docker.
![image](https://github.com/zilliztech/attu/assets/58884839/693c9a2d-4f05-4bcf-8218-0f9fa3e90f6b)
10.224.0.222 is accessible in attu docker

Accessing another url results in the following
http://10.224.0.222:8000/api/v1/healthy  
![image](https://github.com/zilliztech/attu/assets/58884839/64a4da3c-9b65-45bd-8461-e25e0e997fdb)
![image](https://github.com/zilliztech/attu/assets/58884839/8314ab3b-3bb0-4d55-8cf1-c8911c974a38)

**Comment by ycqu** [comment]
> > http://10.224.0.222:8000/#/connect ![image](https://user-images.githubusercontent.com/58884839/275702384-794e8e9b-3848-43ab-9cc0-8023b8dac459.png) Click connect no response, dockers log below ![image](https://user-images.githubusercontent.com/58884839/275702482-f3c032fa-535e-4439-83e0-aed5202d6d18.png)
> > container info: ![image](https://user-images.githubusercontent.com/58884839/275702879-54eba3da-8b87-4375-b2a0-71a1cfbdd156.png)
> > How to solve it?
> 
> make sure the ip `10.224.0.222` can be accessible from the attu docker.

10.224.0.222 is accessible in attu docker
![image](https://github.com/zilliztech/attu/assets/58884839/0815a2b2-8479-4421-b24c-0e5315e0303c)

Accessing another url results in the following
http://10.224.0.222:8000/api/v1/healthy
![image](https://github.com/zilliztech/attu/assets/58884839/3916eb6f-08f9-4c4d-95a1-f6191233ae65)
docker logs：
![image](https://github.com/zilliztech/attu/assets/58884839/c716a59e-db69-4e19-af7b-74a42e421c62)

**Comment by shanghaikid** [comment]
> > > http://10.224.0.222:8000/#/connect ![image](https://user-images.githubusercontent.com/58884839/275702384-794e8e9b-3848-43ab-9cc0-8023b8dac459.png) Click connect no response, dockers log below ![image](https://user-images.githubusercontent.com/58884839/275702482-f3c032fa-535e-4439-83e0-aed5202d6d18.png)
> > > container info: ![image](https://user-images.githubusercontent.com/58884839/275702879-54eba3da-8b87-4375-b2a0-71a1cfbdd156.png)
> > > How to solve it?
> > 
> > 
> > make sure the ip `10.224.0.222` can be accessible from the attu docker.
> 
> 10.224.0.222 is accessible in attu docker ![image](https://user-images.githubusercontent.com/58884839/275705778-0815a2b2-8479-4421-b24c-0e5315e0303c.png)
> 
> Accessing another url results in the following http://10.224.0.222:8000/api/v1/healthy ![image](https://user-images.githubusercontent.com/58884839/275705867-3916eb6f-08f9-4c4d-95a1-f6191233ae65.png) docker logs： ![image](https://user-images.githubusercontent.com/58884839/275705979-c716a59e-db69-4e19-af7b-74a42e421c62.png)

I don't have time to investigate this problem , and your attu & milvus is quite old, please upgrade both of them.

**Comment by jyl087** [comment]
Milvus and attu are both v2.3.1
Both are running in docker.

When I try to login as 'root', password 'Milvus' I get this on the attu logs
`Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
 {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  expose: true,
  statusCode: 403,
  status: 403
}
POST /api/v1/milvus/connect 403 Error: 14 UNAVAILABLE: No connection established

 POST 403 /api/v1/milvus/connect 310.642 ms @ Fri, 20 Oct 2023 07:04:22 GMT ::ffff:172.17.0.1 from undefined Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0 

`

**Comment by mashaonian** [comment]
如果出现Error: Error: 14 UNAVAILABLE: No connection established，这可能是使用wsl连接milvus,因为attu和milvus不再同一个网络下，将attu添加到docker-compose.yml然后再运行docker-compose即可，下面是我将attu添加到docker-compose.yml的部分代码
standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.1.4
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"

  attu:
   container_name: attu
   image: zilliz/attu:v2.2.2
   environment:
     MILVUS_URL: milvus-standalone:19530
   ports:
     - "8000:3000"
   depends_on:
     - "standalone"

networks:
  default:
    name: milvus

**Comment by qiangziakbar** [comment]
出现问题的原因可能是Milvus也是docker运行的，在不适用docker compose的情况下进行如下操作：

## 1. powershell输入ipconfig，查看你自己设备的IPV4地址，如：
172.20.112.1

## 2.重要！修改连接地址
在登陆界面（适用2.4.12）不要用默认的 localhost:19530，而是http://172.20.112.1:19530

-------------------------------------

Here are the steps to address the issue, which might be caused by Milvus also running in Docker without using Docker Compose:

## 1. Open PowerShell and input ipconfig to check the IPV4 address of your device, for example:
172.20.112.1

## 2. Important! Modify the connection address
On the login interface (applicable to version 2.4.12), do not use the default localhost:19530. Instead, use:
http://172.20.112.1:19530
