### ISSUE TITLE
Attu连接失败

### ISSUE THREAD

**Issue by fjt347848167** [zilliztech/attu#250]
**Describe the bug:**
pod中错误信息：POST /api/v1/milvus/connect 400 Error: 14 UNAVAILABLE: No connection established

**Attu version:**
zilliz/attu:v2.2.6

**Comment by fjt347848167** [comment]
(node:48) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: No connection established                                                                                                                                                                                                                                                                                                                                                                                              at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)                                                                                                                                                                                                                                                                                                                                                                                                      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)                                                                                                                                                                                                                                                                                                                                                                                                at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35                                                                                                                                                                                                                                                                                                                                                                                                                  at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)                                                                                                                                                                                                                                                                                                                                                                               at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)                                                                                                                                                                                                                                                                                                                                                                                  at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)                                                                                                                                                                                                                                                                                                                                                                                  at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78                                                                                                                                                                                                                                                                                                                                                                                                                  at processTicksAndRejections (internal/process/task_queues.js:77:11)                                                                                                                                                                                                                                                                                                                                                                                                                  at runNextTicks (internal/process/task_queues.js:64:3)                                                                                                                                                                                                                                                                                                                                                                                                                                at listOnTimeout (internal/timers.js:526:9)                                                                                                                                                                                                                                                                                                                                                                                                                                       for call at                                                                                                                                                                                                                                                                                                                                                                                                                                                                               at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)                                                                                                                                                                                                                                                                                                                                                                                    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)                                                                                                                                                                                                                                                                                                                                                                                    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24                                                                                                                                                                                                                                                                                                                                                                                                     at new Promise (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                                                                          at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)                                                                                                                                                                                                                                                                                                                                                                                         at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:140:38)                                                                                                                                                                                                                                                                                                                                                                        at Generator.next (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                                                                       at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71                                                                                                                                                                                                                                                                                                                                                                                                     at new Promise (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                                                                          at __awaiter (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12)                                                                                                                                                                                                                                                                                                                                                                                     (node:48) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)                                            Error: 14 UNAVAILABLE: No connection established                                                                                                                                                                                                                                                                                                                                                                                                                                          at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)                                                                                                                                                                                                                                                                                                                                                                                                      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)                                                                                                                                                                                                                                                                                                                                                                                                at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35                                                                                                                                                                                                                                                                                                                                                                                                                  at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)                                                                                                                                                                                                                                                                                                                                                                               at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)                                                                                                                                                                                                                                                                                                                                                                                  at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)                                                                                                                                                                                                                                                                                                                                                                                  at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78                                                                                                                                                                                                                                                                                                                                                                                                                  at processTicksAndRejections (internal/process/task_queues.js:77:11)                                                                                                                                                                                                                                                                                                                                                                                                              for call at                                                                                                                                                                                                                                                                                                                                                                                                                                                                               at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)                                                                                                                                                                                                                                                                                                                                                                                    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)                                                                                                                                                                                                                                                                                                                                                                                    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24                                                                                                                                                                                                                                                                                                                                                                                                     at new Promise (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                                                                          at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)                                                                                                                                                                                                                                                                                                                                                                                         at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:192:44)                                                                                                                                                                                                                                                                                                                                                                        at Generator.next (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                                                                       at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71                                                                                                                                                                                                                                                                                                                                                                                                     at new Promise (<anonymous>)                                                                                                                                                                                                                                                                                                                                                                                                                                                          at __awaiter (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12) {                                                                                                                                                                                                                                                                                                                                                                                     code: 14,                                                                                                                                                                                                                                                                                                                                                                                                                                                                             details: 'No connection established',                                                                                                                                                                                                                                                                                                                                                                                                                                                 metadata: Metadata { internalRepr: Map(0) {}, options: {} },                                                                                                                                                                                                                                                                                                                                                                                                                          expose: true,                                                                                                                                                                                                                                                                                                                                                                                                                                                                         statusCode: 400,                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: 400                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

**Comment by fjt347848167** [comment]
(node:48) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24
    at new Promise (<anonymous>)
    at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:140:38)
    at Generator.next (<anonymous>)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12)
(node:48) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)                                           
Error: 14 UNAVAILABLE: No connection established
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /app/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:145:41)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24
    at new Promise (<anonymous>)
    at promisify (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)
    at MilvusClient.<anonymous> (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:192:44)
    at Generator.next (<anonymous>)
    at /app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  expose: true,
  statusCode: 400,
  status: 400
}
