### ISSUE TITLE
loading collection report   Error: TypeError: Cannot read properties of undefined (reading 'emit')

### ISSUE THREAD

**Issue by jsczrangel** [zilliztech/attu#507]
**Describe the bug:**

  GET 200 /api/v1/databases 6.932 ms @ Wed, 22 May 2024 03:55:58 GMT ::ffff:192.168.250.1 from undefined Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 

 

 /app/dist/src/crons/crons.service.js:72

                     throw new Error(error);

                           ^

 

 Error: TypeError: Cannot read properties of undefined (reading 'emit')

     at CronsService.<anonymous> (/app/dist/src/crons/crons.service.js:72:27)

     at Generator.next (<anonymous>)

     at fulfilled (/app/dist/src/crons/crons.service.js:5:58)

     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

 

 Node.js v18.20.1

 error Command failed with exit code 1.

 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.3.10

**Attu version:**

**Comment by shanghaikid** [comment]
it should been fixed in the latest version.
