### ISSUE TITLE
cant not login attu

### ISSUE THREAD

**Issue by nealMS** [zilliztech/attu#524]
**Describe the bug:**
![image](https://github.com/zilliztech/attu/assets/171232777/b40e9cfc-77c7-4714-ba3f-7b8e217b699f)
this is my local, then i can't login next step

![image](https://github.com/zilliztech/attu/assets/171232777/c870f61b-0153-4c3a-8dfe-6f8ae9ef34ce)
Here is a part of my code. This code successfully stores data on localhost:19530.

However, I can't login to Attu.

I am running Attu in Docker with the following command:

sh
코드 복사
docker run -p 8000:3000 -e MILVUS_URL=127.0.0.1:19530 zilliz/attu:latest

And, I am running MilvusDB in Docker with the following commands:

sh
코드 복사
# Download the installation script
curl -sfL https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh

# Start the Docker container
bash standalone_embed.sh start

What else do I need to do to log in?

127.0.0.1:19530 is this wrong?

**Steps to reproduce:**
1.
2.
3.

**Attu version:**
2.4.0

**Comment by nealMS** [comment]
![image](https://github.com/zilliztech/attu/assets/171232777/34cbb486-55ca-4a53-93d3-704e42001546)

Error: Failed to connect to Milvus: Error: 14 UNAVAILABLE: No connection established. Last error: null

then, what is the error?

**Comment by nealMS** [comment]
POST /api/v1/milvus/connect 500 Error: Failed to connect to Milvus: Error: 14 UNAVAILABLE: No connection established. Last error: null
 POST 500 /api/v1/milvus/connect 112.690 ms @ Thu, 30 May 2024 08:33:59 GMT ::ffff:192.168.65.1 from undefined Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 
POST /api/v1/milvus/connect 500 Error: Failed to connect to Milvus: Error: 14 UNAVAILABLE: No connection established. Last error: null
 POST 500 /api/v1/milvus/connect 123.134 ms @ Thu, 30 May 2024 08:34:24 GMT ::ffff:192.168.65.1 from undefined Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 
POST /api/v1/milvus/connect 500 Error: Failed to connect to Milvus: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded after 15.009s,name resolution: 0.002s,Waiting for LB pick
 POST 500 /api/v1/milvus/connect 15157.913 ms @ Thu, 30 May 2024 08:34:57 GMT ::ffff:192.168.65.1 from undefined Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 
 
here is the log to docker

**Comment by shanghaikid** [comment]
where is your milvus installed?

**Comment by shanghaikid** [comment]
just enter `your-ip:19530`. not `127.0.0.1:19530`

**Comment by nealMS** [comment]
milvus installed docker in my mac

like this 

![image](https://github.com/zilliztech/attu/assets/171232777/962b65d8-fb9b-415b-8663-4dccbe4bb374)


and my-ip:19350 is not working

Error: Failed to connect to Milvus: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded after 15.002s,name resolution: 0.001s,Waiting for LB pick

this is error message

**Comment by nealMS** [comment]
i think POST /api/v1/milvus/connect 500 Error 

request is send to server but 500 error response 

i dont know why;

**Comment by shanghaikid** [comment]
can you confirm if you milvus is working?

**Comment by nealMS** [comment]
i change Authentication enabled but is not working

and i try on my code

then console.log() like this

{ status: { error_code: 'Success', reason: '', code: 0 }, value: true }

const collectionExists = await milvusClient.hasCollection({
        collection_name: 'boards',
      });
      
      this one

**Comment by nealMS** [comment]
![image](https://github.com/zilliztech/attu/assets/171232777/1f430813-358b-47ef-b03a-f608603287ff)

Don't get me wrong.

I wrote it this way to hide the IP, but in reality, I entered my IP.

Then, is not working

**Comment by nealMS** [comment]
![image](https://github.com/zilliztech/attu/assets/171232777/917797e5-365c-46ff-a29a-a64e817a2289)

is this right to working milvus in docker command?

**Comment by shanghaikid** [comment]
if your node.js code is working, attu should be working.  can you show me you nodejs code? 

1. restart your attu docker
2. close your browser.
3. open a incognito window, open attu
4. put `your-real-ip:19530` in the address input 
5. connect

**Comment by nealMS** [comment]
https://github.com/zilliztech/attu/issues/161 

i try on this case, but is not helpful;

**Comment by shanghaikid** [comment]
I still thinking this is a network problem.  do you have some vpn opened?

**Comment by nealMS** [comment]
no... is my home, so is not a vpn

**Comment by shanghaikid** [comment]
show me your nodejs code if it is working.

**Comment by nealMS** [comment]
1.restart your attu docker
2.close your browser.
3.open a incognito window, open attu
4.put your-real-ip:19530 in the address input
5.connect

i try this solve, but is some..

![image](https://github.com/zilliztech/attu/assets/171232777/421eaf43-f3ff-496a-8ce8-92ffe5dc1df5)


start pending and few later, is change 500 error

**Comment by shanghaikid** [comment]
```javascript
const milvusClient = new MilvusClient({
    address: 'your-real-ip:19530',
  });

  let res = await milvusClient.getMetric({
    request: { metric_type: 'system_info' },
  });

console.log(res)
```

run this?

**Comment by nealMS** [comment]
![image](https://github.com/zilliztech/attu/assets/171232777/70846719-997a-4611-b4e0-78f830155560)

this is my code

**Comment by shanghaikid** [comment]
> ![image](https://private-user-images.githubusercontent.com/171232777/335116197-70846719-997a-4611-b4e0-78f830155560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjAxNTMsIm5iZiI6MTcxNzA1OTg1MywicGF0aCI6Ii8xNzEyMzI3NzcvMzM1MTE2MTk3LTcwODQ2NzE5LTk5N2EtNDYxMS1iNGUwLTc4ZjgzMDE1NTU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwOTA0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWZjNWE4MmQyMTA2MjgyNjgwOTFkY2U5YTJjMDc4ZjIyZjMxYThjMGUwZTUxYWUxZGQzMWI0YWU4YjA2MGI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OHqznvqV-VH3GqOMlTNJ72bjcM76VrUWMwfHAOzvu34)
> 
> this is my code

show me the client intialization part

**Comment by shanghaikid** [comment]
>const milvusClient = new MilvusClient({
address: 'localhost:19530',
});

you see, you still use localhost

**Comment by nealMS** [comment]
{
  status: {
    extra_info: {},
    error_code: 'Success',
    reason: '',
    code: 0,
    retriable: false,
    detail: ''
  },
  response: {
    nodes_info: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ]
  },
  component_name: 'proxy4'
}

this is the console.log

**Comment by nealMS** [comment]
you mean, chagne the code

const milvusClient = new MilvusClient({
address: '{my-ip}:19530',
});

like this?

**Comment by nealMS** [comment]
but localhost:19530, and then save message to Success

**Comment by shanghaikid** [comment]
> you mean, chagne the code
> 
> const milvusClient = new MilvusClient({ address: '{my-ip}:19530', });
> 
> like this?

yes, localhost is not working for container based attu. you need a real wan ip.   

you enter an ip from your browser, your browser send the ip to the attu server(container), the attu server will try to connect to the ip. but the server is in the container, if you enter `localhost`, that means the container itself, not the milvus server.

**Comment by nealMS** [comment]
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded after 15.000s,name resolution: 0.034s,metadata filters: 0.001s,Waiting for LB pick
    at callErrorFromStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client.ts:360:55)
    at /Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/call-interface.ts:149:27
    at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Grpc.ts:207:15)
    at InterceptingListenerImpl.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/call-interface.ts:145:19)
    at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client.ts:325:42)
    at ServiceClientImpl.<anonymous> (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at /Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Function.ts:37:21
    at new Promise (<anonymous>)
    at /Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Function.ts:34:10
    at Generator.next (<anonymous>)
    at fulfilled (/Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    
  i change on my code, like this. const milvusClient = new MilvusClient({ address: '{my-ip}:19530', });

  then, it make happne to error..

**Comment by shanghaikid** [comment]
> Error: 4 DEADLINE_EXCEEDED: Deadline exceeded after 15.000s,name resolution: 0.034s,metadata filters: 0.001s,Waiting for LB pick at callErrorFromStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/call.ts:82:17) at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client.ts:360:55) at /Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/call-interface.ts:149:27 at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Grpc.ts:207:15) at InterceptingListenerImpl.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/call-interface.ts:145:19) at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34) at Object.onReceiveStatus (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48) at /Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24 at processTicksAndRejections (node:internal/process/task_queues:77:11) for call at at ServiceClientImpl.makeUnaryRequest (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/client.ts:325:42) at ServiceClientImpl. (/Users/minsu/Project/startup_wing_server/node_modules/@grpc/grpc-js/src/make-client.ts:189:15) at /Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Function.ts:37:21 at new Promise () at /Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Function.ts:34:10 at Generator.next () at fulfilled (/Users/minsu/Project/startup_wing_server/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:5:58) at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> i change on my code, like this. const milvusClient = new MilvusClient({ address: '{my-ip}:19530', });
> 
> then, it make happne to error..

so this make sense. 

you realip:19530 is not pointed to  your milvus server.   :< ... you need an ip that pointed to the milvus server address.

**Comment by shanghaikid** [comment]
run `ifconfig` , find your wan ip. 

use that ip

**Comment by shanghaikid** [comment]
Attu is running in the container.  
The container is like a machine, it has its own network. 
You enter an ip through you web browser.
The web browser send a request to the Attu container.
The Attu container is trying to connect to that ip from the container. 
But the container has it's own networking, if you enter `localhost`, that means the container's network.

So all you need is to find a milvus ip that Attu container can access.

**Comment by nealMS** [comment]
hmm.. thank for your answer 
i try on my ip to docker 
and if i see the problem then i comment this page :)

**Comment by nealMS** [comment]
and, more question 

<img width="837" alt="image" src="https://github.com/zilliztech/attu/assets/171232777/aa51699a-5d78-4eca-ac4e-c1cf3a996ec9">

http://localhost:8000/api/v1/milvus/version

this is not milvus server?

is response Success 200, then i dont know why

http://localhost:8000/api/v1/milvus/version -> 200 Success
http://localhost:8000/api/v1/milvus/connect -> 500 server error

**Comment by shanghaikid** [comment]
> and, more question
> 
> <img alt="image" width="837" src="https://private-user-images.githubusercontent.com/171232777/335419849-aa51699a-5d78-4eca-ac4e-c1cf3a996ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDkzNzAsIm5iZiI6MTcxNzE0OTA3MCwicGF0aCI6Ii8xNzEyMzI3NzcvMzM1NDE5ODQ5LWFhNTE2OTlhLTVkNzgtNGVjYS1hYzRlLWMxY2YzYTk5NmVjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwOTUxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzA5ZDI4OTNkNGQxYWJmMmU0ZGRiM2ZiM2UyNTEwZmM1ZGU5ZmJlYTNiMWIxNDk3MjFlNzNjNzBiZTQ0MzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ucsw5ZCrGgqIunQ2_1A_9Yite_UkpWb_nL80rqNabqQ">
> http://localhost:8000/api/v1/milvus/version
> 
> this is not milvus server?
> 
> is response Success 200, then i dont know why
> 
> http://localhost:8000/api/v1/milvus/version -> 200 Success http://localhost:8000/api/v1/milvus/connect -> 500 server error

The version api is deprecated.  it doesn't send request any more.

**Comment by nealMS** [comment]
Jesus, as you advised, I uploaded Milvus to the cloud and logged in, and it works well.

Thank you for your response!!

<img width="1273" alt="image" src="https://github.com/zilliztech/attu/assets/171232777/bfec75df-9a05-4304-8447-c9e04e1372b9">
