### ISSUE TITLE
milvus is 2.4.6 ,attu v2.4.8 connect failed

### ISSUE THREAD

**Issue by lghgf123** [zilliztech/attu#646]
**Describe the bug:**

I can not connect milvus by attu V2.4.8 or V2.4.7

**Steps to reproduce:**
1.
2.
3.

**Attu version:**

**Attu version:**

**Comment by shanghaikid** [comment]
https://github.com/zilliztech/attu/issues/613 same?

**Comment by lghgf123** [comment]
> [第613章](https://github.com/zilliztech/attu/issues/613)一样吗？



> #613 same?

Not same ,I can connect milvus by attu V2.2.8

**Comment by shanghaikid** [comment]
what is your milvus version?

**Comment by lghgf123** [comment]
> what is your milvus version?
v2.4.6, milvus and attu all use docker run

**Comment by shanghaikid** [comment]
any error?

**Comment by lghgf123** [comment]
> any error?

return 303

**Comment by weijingwei** [comment]
![image](https://github.com/user-attachments/assets/f04be3f9-ed2c-441e-8fcd-a183fe4e9c37)
this is mine

**Comment by shanghaikid** [comment]
> ![image](https://private-user-images.githubusercontent.com/16864673/372349290-f04be3f9-ed2c-441e-8fcd-a183fe4e9c37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjU0NTAsIm5iZiI6MTcyNzc2NTE1MCwicGF0aCI6Ii8xNjg2NDY3My8zNzIzNDkyOTAtZjA0YmUzZjktZWQyYy00NDFlLThmY2QtYTE4M2ZlNGU5YzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA2NDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MjI4NzE0MmFhYzIxMzY2NjJjMGMyZjU3ZDA3ZGZiNzY5YjRmMDIwYjg4OTliMTc1NWJhODFkODJmMGJmMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hzw2CxTbTmqBXTgUvTyNbOECxYG6VlAlcIymXVh10wg) this is mine

if you are using docker, please don't use localhost, use real IP of your milvus server.

**Comment by shanghaikid** [comment]
> getting same issue unable to connect

1. docker or app
2. milvus version
3. are you trying to connecting to a none default database?

**Comment by imuhammadarsalan** [comment]
i manage to connect, thanks for the help,

i want to know how can i load data based partition there is no option to do that. Can you please also help with that ?

**Comment by shanghaikid** [comment]
> i manage to connect, thanks for the help,
> 
> i want to know how can i load data based partition there is no option to do that. Can you please also help with that ?

Attu doesn't support this operation yet.

**Comment by imuhammadarsalan** [comment]
Hello my milvus standalone service container is running perfectly aftera minutue it is getting down with this logs of details 
milvus-standalone | goroutine 739 [select]:
milvus-standalone | runtime.gopark(0xc000a65568?, 0x2?, 0xc0?, 0x38?, 0xc000a65534?)
milvus-standalone |     /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000a653b8 sp=0xc000a65398 pc=0x1e6dc0e
milvus-standalone | runtime.selectgo(0xc000a65568, 0xc000a65530, 0x87f9940?, 0x0, 0x2?, 0x1)
milvus-standalone |     /usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc000a654d8 sp=0xc000a653b8 pc=0x1e7e665
milvus-standalone | github.com/milvus-io/milvus/pkg/util/retry.Handle({0x60ac008, 0xc002aa0af0}, 0xc000a65898, {0xc000a65788, 0x3, 0x1?})
milvus-standalone |     /workspace/source/pkg/util/retry/retry.go:127 +0x40b fp=0xc000a65698 sp=0xc000a654d8 pc=0x2dfdccb
milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call(0x6135460, {0x60ac008, 0xc002aa0af0}, 0xc0025c8db0)
milvus-standalone |     /workspace/source/internal/util/grpcclient/client.go:466 +0x5ad fp=0xc000a65900 sp=0xc000a65698 pc=0x4747bcd
milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call(0x6135460, {0x60ac078, 0xc0029fff10}, 0xc0005f4001)
milvus-standalone |     /workspace/source/internal/util/grpcclient/client.go:553 +0x85 fp=0xc000a65a98 sp=0xc000a65900 pc=0x4747205
milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall(...)
milvus-standalone |     /workspace/source/internal/util/grpcclient/client.go:569
milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall({0x60ac078?, 0xc0029fff10?}, 0x55a9200?)
milvus-standalone |     /workspace/source/internal/util/grpcclient/client.go:567 +0x39 fp=0xc000a65ad0 sp=0xc000a65a98 pc=0x474ae99
milvus-standalone | github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]({0x60ac078, 0xc0029fff10?}, 0xc000f037a0, 0xc00259bbe0)
milvus-standalone |     /workspace/source/internal/distributed/datacoord/client/client.go:107 +0xad fp=0xc000a65b08 sp=0xc000a65ad0 pc=0x474cb8d
milvus-standalone | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetMetrics(0xc000f037a0, {0x60ac078?, 0xc0029fff10}, 0x0?, {0x0?, 0x0?, 0x0?})
milvus-standalone |     /workspace/source/internal/distributed/datacoord/client/client.go:402 +0x1f8 fp=0xc000a65bb8 sp=0xc000a65b08 pc=0x473f558
milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.getDataCoordMetrics({0x60ac078, 0xc0029fff10}, {0x6136fb0, 0xc000f037a0})
milvus-standalone |     /workspace/source/internal/rootcoord/util.go:257 +0x71 fp=0xc000a65c10 sp=0xc000a65bb8 pc=0x4e9ffd1
milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).collectMetrics.func2()
milvus-standalone |     /workspace/source/internal/rootcoord/quota_center.go:431 +0x4a fp=0xc000a65f78 sp=0xc000a65c10 pc=0x4e5b5aa
milvus-standalone | golang.org/x/sync/errgroup.(*Group).Go.func1()
milvus-standalone |     /go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 +0x56 fp=0xc000a65fe0 sp=0xc000a65f78 pc=0x327aa16
milvus-standalone | runtime.goexit()
milvus-standalone |     /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000a65fe8 sp=0xc000a65fe0 pc=0x1ea3441
milvus-standalone | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 538
milvus-standalone |     /go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:72 +0x96
milvus-standalone exited with code 134

**Comment by imuhammadarsalan** [comment]
another issue whevever i try to login i am redirect to login screen with a message of "ForbiddenError: Can not find your connection, please check your connection settings." i can see i am successfully login and i got user id from network tab..

**Comment by shanghaikid** [comment]
> **Hello my milvus standalone service container is running perfectly aftera minutue it is getting down with this logs of details**
> 
> milvus-standalone | goroutine 739 [select]: milvus-standalone | runtime.gopark(0xc000a65568?, 0x2?, 0xc0?, 0x38?, 0xc000a65534?) milvus-standalone | /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc000a653b8 sp=0xc000a65398 pc=0x1e6dc0e milvus-standalone | runtime.selectgo(0xc000a65568, 0xc000a65530, 0x87f9940?, 0x0, 0x2?, 0x1) milvus-standalone | /usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc000a654d8 sp=0xc000a653b8 pc=0x1e7e665 milvus-standalone | github.com/milvus-io/milvus/pkg/util/retry.Handle({0x60ac008, 0xc002aa0af0}, 0xc000a65898, {0xc000a65788, 0x3, 0x1?}) milvus-standalone | /workspace/source/pkg/util/retry/retry.go:127 +0x40b fp=0xc000a65698 sp=0xc000a654d8 pc=0x2dfdccb milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).call(0x6135460, {0x60ac008, 0xc002aa0af0}, 0xc0025c8db0) milvus-standalone | /workspace/source/internal/util/grpcclient/client.go:466 +0x5ad fp=0xc000a65900 sp=0xc000a65698 pc=0x4747bcd milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).Call(0x6135460, {0x60ac078, 0xc0029fff10}, 0xc0005f4001) milvus-standalone | /workspace/source/internal/util/grpcclient/client.go:553 +0x85 fp=0xc000a65a98 sp=0xc000a65900 pc=0x4747205 milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall(...) milvus-standalone | /workspace/source/internal/util/grpcclient/client.go:569 milvus-standalone | github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase[...]).ReCall({0x60ac078?, 0xc0029fff10?}, 0x55a9200?) milvus-standalone | /workspace/source/internal/util/grpcclient/client.go:567 +0x39 fp=0xc000a65ad0 sp=0xc000a65a98 pc=0x474ae99 milvus-standalone | github.com/milvus-io/milvus/internal/distributed/datacoord/client.wrapGrpcCall[...]({0x60ac078, 0xc0029fff10?}, 0xc000f037a0, 0xc00259bbe0) milvus-standalone | /workspace/source/internal/distributed/datacoord/client/client.go:107 +0xad fp=0xc000a65b08 sp=0xc000a65ad0 pc=0x474cb8d milvus-standalone | github.com/milvus-io/milvus/internal/distributed/datacoord/client.(*Client).GetMetrics(0xc000f037a0, {0x60ac078?, 0xc0029fff10}, 0x0?, {0x0?, 0x0?, 0x0?}) milvus-standalone | /workspace/source/internal/distributed/datacoord/client/client.go:402 +0x1f8 fp=0xc000a65bb8 sp=0xc000a65b08 pc=0x473f558 milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.getDataCoordMetrics({0x60ac078, 0xc0029fff10}, {0x6136fb0, 0xc000f037a0}) milvus-standalone | /workspace/source/internal/rootcoord/util.go:257 +0x71 fp=0xc000a65c10 sp=0xc000a65bb8 pc=0x4e9ffd1 milvus-standalone | github.com/milvus-io/milvus/internal/rootcoord.(*QuotaCenter).collectMetrics.func2() milvus-standalone | /workspace/source/internal/rootcoord/quota_center.go:431 +0x4a fp=0xc000a65f78 sp=0xc000a65c10 pc=0x4e5b5aa milvus-standalone | golang.org/x/sync/errgroup.(*Group).Go.func1() milvus-standalone | /go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 +0x56 fp=0xc000a65fe0 sp=0xc000a65f78 pc=0x327aa16 milvus-standalone | runtime.goexit() milvus-standalone | /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000a65fe8 sp=0xc000a65fe0 pc=0x1ea3441 milvus-standalone | created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 538 milvus-standalone | /go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:72 +0x96 milvus-standalone exited with code 134

I don't think this is about attu, i may open a ticket on https://github.com/milvus-io/milvus.io

**Comment by sunhaha123** [comment]
fucking problem always!
